name = "nuxt-worker"
type = "javascript"
account_id = "bf3bb41c3094e59251158b0bd2b296e3"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "true"
upload.format = "service-worker"
